[package]
name = "optimized-trie"
version = "0.1.0"
authors = ["Clament <clament.john.k@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "countwords"
path = "main.rs"

[profile.release]
debug = true